# Generated by Django 4.2.4 on 2023-08-20 23:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('internals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_park', models.BooleanField()),
                ('is_tourist_attraction', models.BooleanField()),
                ('is_point_of_interest', models.BooleanField()),
                ('is_establishment', models.BooleanField()),
                ('place_id', models.CharField(max_length=100)),
                ('latitude', models.CharField(max_length=100)),
                ('longitude', models.CharField(max_length=100)),
                ('data', models.CharField(blank=True, max_length=10000, null=True)),
                ('rating', models.IntegerField()),
                ('number_of_ratings', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('vicinity', models.CharField(max_length=100)),
                ('zip_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='internals.zipcode')),
            ],
            options={
                'unique_together': {('zip_code', 'place_id')},
            },
        ),
    ]
