# Generated by Django 4.2.4 on 2023-08-21 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internals', '0002_attraction'),
    ]

    operations = [
        migrations.AddField(
            model_name='attraction',
            name='photo_reference',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
